branches:
  only:
    - master
    - testing
language: python
python:
    - "2.7"
install:
    - "pip install -r requirements.txt"
script:
    - "python manage.py test BearClubs.bc.tests.unit"
notifications:
  email:
    recipients:
      - pkillian@berkeley.edu
    on_success: change
    on_failure: always

