language: python
python:
    - "2.7.6"
env:
    - DJANGO=1.6.2
install:
    - pip install -r requirements.txt --use-mirrors
before_script:
    - python manage.py syncdb
script:
    - python manage.py test

